# Generated by Django 5.0.4 on 2024-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='em andamento', max_length=50),
        ),
    ]
